### ISSUE TITLE
Zoom does no longer work

### ISSUE THREAD

**Issue by scherers** [scherers/UKBB_EMG_Analysis#4]
After creating new *_eval.csv files the zoom button does no longer work:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(*args)
  File "/home/scherers/Documents/Software/UKBB_EMG_Analysis/emg_visualizer.py", line 658, in _zoom_in
    self.multi_cursor.disconnect()
AttributeError: 'MultiCursor' object has no attribute 'disconnect'
```

I have no idea why! What went wrong?

**Comment by mabuch** [comment]
This is caused by my attempts to make it python3 compatible.
Prior, the MultiCursors and SpanSelectors were simply "overwritten" (new Instances to the same variable), when changing modes. But in python3 the old instances were still running (I guess because of different garbage-collection behaviour), which caused problems. Therefore I had to disconnect the old MultiCursors and SpanSelectors from the plots before creating the new ones. I also tested it on python 2.7 and it worked, therefore I guess this is again a problem regarding your older matplotlib-version.
As a quick and dirty Bugfix, you can simply delete the `self.multi_cursor.disconnect()` lines (there are 3 of them: ZOOM, ADD, DEL)

**Comment by scherers** [comment]
I'm fairly sure that the UKBB runs under the same version than I do.
So I prefer a proper fix.
